### ISSUE TITLE
nx-parallel v0.3 not available yet

### ISSUE THREAD

**Issue by Schefflera-Arboricola** [conda-forge/nx-parallel-feedstock#5]
### Comment:

I recently merged PR https://github.com/conda-forge/nx-parallel-feedstock/pull/4 which updated the version to 0.3(for reference - [nx-parallel v0.3 on pypi](https://pypi.org/project/nx-parallel/)). But, on the anaconda website ([here](https://anaconda.org/conda-forge/nx-parallel)) it is still v0.2. 

Could you please provide insight into why the update isn’t reflected yet? Is there usually a delay, or have I done something wrong in the last PR? I did add some extra commits to it because we have switched from hatchling to setuptools in v0.3 and I also added various dependencies that got added in this version.

cc @MridulS 

Thanks!

**Comment by MridulS** [comment]
https://anaconda.org/conda-forge/nx-parallel has the 0.3 release now :)
